### ISSUE TITLE
Query predicate DSL for simple case classes and atomic types

### ISSUE THREAD

**Issue by adamstarlight** [adamstarlight/iris#1]
Predicate DSL allows user to easily intuitive queries with a help of a compiler typechecking.

## Expected behavior
**GIVEN** User has a case class with only built-in atomic type properties (like Int, String and so on) with `@Record` annotation applied
```scala
@Record case class User(username: String, age: Int)
```
**THEN** `User` object should be created or extended with a member of type `RecordField` for each of original case class member
**WHEN** User wants to create a predicate for any field of a case class
```scala
User.username === "bestuser"
```
**THEN** compiler should see all child members of case class inside generated object with the same name
**AND** autocomplete (only Metals for now) should help user fill member field name
**AND** compiler should prevent user from supplying incompatible operand for comparison
```scala
User.username === 4 // This should not compile
```
**AND** expression result should be of type `Predicate` and represent initial clause user wanted

## Implementation
Expected implementation of `@Record` annotation is to create or extend case class companion object with members of type `RecordField` for each case class property. Generated code should not override existing companion contents. Notice that `RecordField`'s are typed according to original member type.
```scala
@Record case class User(username: String, age: Int)

// Should expand to
object User {
  val username: RecordField[String] = new RecordField[String]("username")
  val age: RecordField[Int] = new RecordField[Int]("age")
}
```
## Todo
- [x] Tests are written
- [x] `RecordField` class with `===` operator is implemented
- [x] Macro annotation works
- [x] All tests pass
