### ISSUE TITLE
Query Predicate DSL relational operators

### ISSUE THREAD

**Issue by adamstarlight** [adamstarlight/iris#2]
Predicates allow to compare a field value with operand using a different types of comparison operators.
## Expected behavior
**GIVEN** user has a case class with only built-in atomic type properties (like Int, String and so on) with @Record annotation applied
```scala
@Record case class User(username: String, age: Int)
```
**WHEN** user wants to compare field value with operand of compatible type
```scala
User.username === "Jhon"
```
**THEN** code should compile and produce a valid predicate
**WHEN** user wants to check if field value is present in non empty sequence passed as an operand
```scala
User.age in Seq(10, 20, 30, 40)
```
**THEN** code should compile and produce a valid predicate
**WHEN** `in` clause operand is equal to `Nil`
**THEN** the `InvalidArgumentException` should be thrown
**WHEN** user want to compare field value with an operand of incompatible type
```scala
User.username === 4
```
**THEN** compilation should result in error
## Todo
- [x] Tests are written
- [x] Basic checks for equality `===`, `!==`, `<`, `<=`, `>`, `>=` are implemented
- [x] Value in a list check `in` is implemented
- [x] All tests pass
