### ISSUE TITLE
Query Predicate DSL array comparison support

### ISSUE THREAD

**Issue by adamstarlight** [adamstarlight/iris#3]
## Expected behavior
**GIVEN** user has a case class with a sequence property that can be iterated on (like List, Seq and so on) with @record annotation applied
```scala
@Record case class User(username: String, age: Int, roles: List[String])
```
**THEN** roles field in generated companion object should have type `RecordSeqField` instead of `RecordField`
**AND** `RecordSeqField` should have overloaded `in` method. This method allows to check if field values are contained in operand of sequence type, functions similar to postgreSQL `<@` operator
**AND** `RecordSeqField` should have method `contains`. This method functions similar to postgreSQL `@>` operator
## Todo
- [ ] Tests are written
- [ ] `in` method overload is implemented
- [ ] `contains` method is implemented
- [ ] All tests passes
