### ISSUE TITLE
Doobie driver find queries with ZIO

### ISSUE THREAD

**Issue by adamstarlight** [adamstarlight/iris#9]
Implement a working doobie driver for simple `find` queries for `AnyVal` types.
## Expected behavior
**GIVEN** user has a case class with a sequence property that can be iterated on (like List, Seq and so on) with `@Record` annotation applied
```scala
@Record case class User(username: String, age: Int, roles: List[String])
```
**AND** user created a `Repository` instance for `User` using doobie postgres backend
```scala
class UserRepository(conn: PostgresConnection) extends PostgresRepository[User](conn)
```
**AND** a postgres database has a table called `users`
**WHEN** user creates a valid search expression
```scala
val conn = ...
val users = new UserRepo(conn)
val task: Task[List[User]] = users.find(username === "Bob").exec
val rows = runtime.unsafeRun(task)
```
**THEN** `rows` variable should contain one or more records of type User with username Bob
**WHEN** something goes wrong
**THEN** task should fail with error
## Todo
- [x] Subproject `iris-doobie-zio` is created
- [x] Test framework support working with embedded database
- [ ] Traits are written
- [ ] Tests are written
- [ ] All tests pass
